### ISSUE TITLE
Request Deprecation

### ISSUE THREAD

**Issue by brianferri** [csunibo/cs-discord-bot#2]
**Is your feature request related to a problem? Please describe.**
request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
the code needs to be refactored in order to improve maintainability and future expandability.
the `scrape.js` modules are all based on request and need to be remade from scratch

**Describe the solution you'd like**
Find an alternative to request and rebase the code from there

**Describe alternatives you've considered**
axios is already used and implemented if it's a plausible alternative

Edit:
This gives offspring to some other issues with har-validator and uuid as well

**Comment by foxyseta** [comment]
OP dropped out.
